module.exports = {
  animation: require("./animation"),
  background: require("./background"),
  border: require("./border"),
  "box-shadow": require("./box-shadow"),
  clipping: require("./clipping"),
  color: require("./color"),
  columns: require("./columns"),
  content: require("./content"),
  cursor: require("./cursor"),
  dimensions: require("./dimensions"),
  display: require("./display"),
  flexbox: require("./flexbox"),
  float: require("./float"),
  grid: require("./grid"),
  list: require("./list"),
  margin: require("./margin"),
  padding: require("./padding"),
  position: require("./position"),
  table: require("./table"),
  transition: require("./transition"),
  typography: require("./typography"),
};
